### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by guyisra** [nomad/houston#101]
With issues for persistance and complex workarounds..

Is this still maintained / the go-to push notification gem?

**Comment by pkuruppu** [comment]
+1
I'm curious if there's similar gems besides this or Grocer that are regularly maintained.

**Comment by blakeperdue** [comment]
+1 @mattt is usually responsive with issues on his repos, so I would think this is still maintained.

**Comment by drmrlong** [comment]
+1 as well.

He's normally responsive, but I know he's turned over both NSHipster and Alamofire to other people.  He also hasn't commited anything since June: https://github.com/mattt/

**Comment by blakeperdue** [comment]
@drmrlong @pkuruppu @guyisra looks like this is not being maintained. Perhaps someone could take over maintaining it from @mattt 

Does anyone have any good ideas on who might be interested in owning this?

**Comment by tipycalFlow** [comment]
@mattt  Is the upcoming HTTP/2 API port in the pipeline?

**Comment by beauby** [comment]
I personally don't have enough time to commit to maintaining this gem, but I'd be interested in contributing to a maintained fork.

**Comment by beatrupp** [comment]
I think he is not allowed to contribute to OSS anymore since he is working at Apple. 
See this [thread on Reddit](https://www.reddit.com/r/iOSProgramming/comments/6shrsj/what_the_hell_happened_to_mattt_thompson/).

**Comment by KrauseFx** [comment]
Also, you can check out [fastlane.tools](https://fastlane.tools) together with [spaceship.airforce](https://spaceship.airforce) 👍
