### ISSUE TITLE
How are response codes being used?

### ISSUE THREAD

**Issue by pkuruppu** [nomad/houston#104]
I noticed that Apple response codes are stored in module Houston, class Notification. Are these response codes being used? And if so, where are they being stored? 

It appears that if I try to send a notification to a bad token, Houston::Client.production.devices briefly stores the token, but I'm not sure for what reason the token failed. Is there a way to return the response codes returned as feedback?

**Comment by dankimio** [comment]
Are you talking about [feedback service](https://github.com/nomad/houston#feedback-service)?

**Comment by ltrainpr** [comment]
👍  
@dankimio Seems like Apple is moving away from [feedback service](http://stackoverflow.com/a/34631670/2226172).  Seems like applications should be handling 410 response codes now.
