### ISSUE TITLE
Safari Push Notifications

### ISSUE THREAD

**Issue by AlvaroOlivencia** [nomad/houston#110]
Hi,
does this GEM work with Safari Push Notifications ?
https://developer.apple.com/library/mac/documentation/NetworkingInternet/Conceptual/NotificationProgrammingGuideForWebsites/PushNotifications/PushNotifications.html#//apple_ref/doc/uid/TP40013225-CH3-SW1

Thanks

**Comment by dankimio** [comment]
Hello. Currently, it doesn't support Safari Push Notifications.

**Comment by nijeesh4all** [comment]
Is the safari push notifications has been implemented ?

**Comment by dankimio** [comment]
No, but we would gladly accept a PR with that feature.
