### ISSUE TITLE
How to increment the badge number?

### ISSUE THREAD

**Issue by nbastoWM** [nomad/houston#112]
I'm using this with React Native and everything is fine except for the incrementation of the badge number.  

I tried to send `notification.badge = +1` or  `notification.badge = "+1"` but the badge number is always just 1.

I can't previously know what badge number is on the device so I can't send the exact number.

**Comment by bengg** [comment]
You cannot increment the badge number. You can only set a new badge number each push notifications.

**Comment by maxprig** [comment]
You must implement logic for increment badge in you Ruby application.
