### ISSUE TITLE
OpenSSL::SSL::SSLError: SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read server session ticket A

### ISSUE THREAD

**Issue by pniemczyk** [nomad/houston#114]
``` ruby
    from /app/vendor/bundle/ruby/2.3.0/gems/houston-2.2.3/lib/houston/connection.rb:44:in `connect'
    from /app/vendor/bundle/ruby/2.3.0/gems/houston-2.2.3/lib/houston/connection.rb:44:in `open'
    from /app/app/components/apn_service/connection.rb:14:in `initialize'
    from /app/app/components/apn_service/connection.rb:8:in `new'
    from /app/app/components/apn_service/connection.rb:8:in `window'
    from /app/app/components/apn_service.rb:4:in `send_notification'
```

`OpenSSL 1.0.1f 6 Jan 2014`
Recently, in my application I began to appear occasionally this error. Any ideas how to solve this problem ?

**Comment by stinju** [comment]
We're also having the same issue - started roughly on 4/8.  Some related threads:

https://forums.developer.apple.com/thread/44677
https://github.com/grocer/grocer/issues/88

**Comment by pniemczyk** [comment]
Maybe we should send each error stack trace to the Apple Support :D

**Comment by schnmudgal** [comment]
Same here. Getting my 70-90% push requests FAILED. Tried replacing certificates too. But in vain!

**Comment by sborsje** [comment]
Same here! Also tried rotating the certificates, but no luck so far. There's another thread here: https://forums.developer.apple.com/message/130478

**Comment by pniemczyk** [comment]
I'm updated ruby to 2.3.0 and generated certs one more time with latest OpenSSL. It seems that errors were gone.

**Comment by jmagoon** [comment]
@pniemczyk by latest openssl do you mean what is built by apple (0.9.8) or the latest openssl release (1.0.2g)?

**Comment by himberjack** [comment]
Guys, are you on AWS by any chance? could that be related?

**Comment by pniemczyk** [comment]
@jmagoon it seems that the errors began appearing again. So updating rails and regenerating certs is useless. Only for while it was ok

**Comment by schnmudgal** [comment]
Yes. Using AWS only. Just to inform, my staging AWS(Ubuntu 14) is throwing this error in about 50-70% of requests. But my production AWS(Ubuntu 14) is giving it in about 2-5% of request only.
And my local Mac is not giving this error at all.
Tried re-generating certificates, even directly form opnessl of staging server itself, but not gain.

**Comment by jmagoon** [comment]
We are on Heroku (and therefore AWS)--and that's the only place we see the
errors. No errors for us on local machines.

**Comment by himberjack** [comment]
I must say that we have another ssl issue in aws where our apps
sporadically claim they cannot handshake ssl with our elb. Amazon say its
not on their side. Im just doing 1+1 so please open tickets on amazon
support. For sure they have something going on with ssl

**Comment by schnmudgal** [comment]
I think the issue have been resolved now (temporarily maybe). As I didn't do anything, and just brut forced 10,000 push notifications via looping on my server which were failing 50-70% of my pushes, but this time, not a single failed out of 10,000.

**Comment by sborsje** [comment]
We've noticed a huge drop in failures since last Wednesday too.

**Comment by Dorian** [comment]
It started appearing again yesterday, maybe related to the big AWS outage

**Comment by schnmudgal** [comment]
@Dorian - I don't think it's because of AWS in any way. As AWS outage was specifically related to S3. And secondly, it's related to Apple servers more, than AWS servers and I guess Apple must be having it's own servers and not on AWS ec2s etc., I guess(I literally guess).

**Comment by Dorian** [comment]
I'm gonna dig deeper into testing the server to server connection, anybody has any SSL configuation recommendations for those servers?

- Gateway: `apn://gateway.push.apple.com:2195`
- Feedback: `apn://feedback.push.apple.com:2196`

**Comment by Dorian** [comment]
Peak of errors yesterday for instance:

<img width="451" alt="screen shot 2017-04-04 at 12 15 57" src="https://cloud.githubusercontent.com/assets/129149/24674503/8278b8a6-1930-11e7-8752-8103f2734865.png">

**Comment by Dorian** [comment]
Solution was to upgrade to openssl `1.0.2g-1​ubuntu4.6` (from `1.0.1f-1​ubuntu2.21`) (e.g. from `cedar-14` to `heroku-16` stack).

```
heroku stack:set heroku-16 -a your-app
```

And in `app.json`:

```
{
...
"stack": "heroku-16",
...
}
```

**Comment by dankimio** [comment]
Can everyone confirm that this fixes the problem?
