### ISSUE TITLE
Latest release and README

### ISSUE THREAD

**Issue by pavloo** [nomad/houston#115]
Hey. First of all, thanks for your great work on the library. Now about the problem I faced: 

Looks like the latest release (the one tagged on github and published to `rubygems`) was done significant time ago, and since that time master branch accumulated some changes that are not yet published. It's okay, there must be some reasons for that. But the problem is that `README` already contains these new changes, and by using the latest release user assumes that he/she gets all the features mentioned in `README`. In my particular case, I was struggling with the feature of specifying the certificate (as a string) in ENV variable: the feature was in `README`, but not in the latest release (2.2.3) - and I couldn't figure out, what was wrong. 

Thank you.

**Comment by dankimio** [comment]
I'm working on it right now. Had the same issue.
