### ISSUE TITLE
Command line "apn push -e production" Works; Production code does not with same pem

### ISSUE THREAD

**Issue by rankinit** [nomad/houston#116]
Ruby 2.2
Rails 4

I followed the example code to send production notifications which does not work. However command line "apn push -e production.... " works.   What do I have to do to get the production push code notifications working using the example code?

Obv. the example code was not copied verbatim ... the relevant device token & messages were changed.
Currently I use the following code to send push notifications in production:

system "apn push \"#{device_token}\" -e production  -c pro.pem  -m \"#{message}\""

**Comment by markpuck** [comment]
I am experiencing this issue as well. 
apn command line works fine. system "apn ..." also works fine (no surprise). Just not getting any notifications sent using using Houston APN.

Anything else to verify, check? I hacked in a bunch of debug logging in Houston client.rb and no errors are returned, etc.

ruby version: ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
Houston gem: 2.2.3

**Comment by oscarguinane** [comment]
I'm having the same issue, here's the code, anything look off?

```
def send_push_notification notification_id
  notification = Notification.find( notification_id )

  if notification.receiver[:device_token].blank?
    Rails.logger.error 'The receiver has no device token.'
  elsif notification.receiver[:operating_system].to_s[/iOS/i].present?
    # Create a pn that alerts a message to the user, plays a sound, and sets the badge on the app.
    pn = Houston::Notification.new(
      device:            notification.receiver.device_token,
      alert:             notification.subject,
      badge:             1,
      category:          notification.purpose,
      priority:          1,
      content_available: true,
      custom_data:       {
        id_1: notification.try( :id_1 ),
        id_2: notification.try( :id_2 ),
        id_3: notification.try( :id_3 )
      }.to_json
    )

    # iOS has an enterprise configuration which requires both environment certificates to be tried.
    if Rails.env.production?
      apn = Houston::Client.production
      apn.certificate = File.read( "/certs/pn-prod.pem" )
    else
      apn = Houston::Client.development
      apn.certificate = File.read( "/certs/pn.pem" )
    end

    apn.passphrase = ''

    apn.push( pn )
  end
end
```

**Comment by Pourliver** [comment]
I experience the same issue where it works in the CLI with -e, -c and -m all set, but not sending from a persistent connection.

I logged all I could, and I receive no errors on the backend.

I ran out of ideas. Anyone managed to fix this?

houston (2.2.3)

**Comment by markpuck** [comment]
A year later, I've found 2 tokens that work opposite of each other.  Only Houston APN can send notifications to 1 of them, and only apn command-line can send to the other token.  Both are running on the same production box.  

Has anybody else seen this issue?  Any suggestions?
