### ISSUE TITLE
"1 push notification sent successfully" from terminal but I am sure I didn't get the push notification

### ISSUE THREAD

**Issue by qiulang** [nomad/houston#125]
I run the command 

```
localhost:xxxx
$ apn push "<835af111729153d884612dcac613aa57dcabddf9b08a68a177d8325c48a1f6f4>" -c ./voip_push.pem -m "Hi Houston"
1 push notification sent successfully
```

But I am sure I didn't got the push because I then used pushwoosh push test wirh the same token, and I got the token. What can the possible reason ?

**Update**

This is a VOP push token, not the normal APN token so I realized I should use production enviroment, so I changed to:

```
apn push "835af111729153d884612dcac613aa57dcabddf9b08a68a177d8325c48a1f6f4"  -e production -c voip_push.pem -m "Houston:13910134045"
1 push notification sent successfully
```

But still no push received.

**Comment by qiulang** [comment]
It doesn't matter when I change token format:

localhost:xxxx$ apn push "<835af111 729153d8 84612dca c613aa57 dcabddf9 b08a68a1 77d8325c 48a1f6f4>" -c ./voip_push.pem -m "Houston:13910134045"
1 push notification sent successfully

or 

localhost:emicnet qiulang$ apn push "835af111729153d884612dcac613aa57dcabddf9b08a68a177d8325c48a1f6f4" -c ./voip_push.pem -m "Houston:13910134045"
1 push notification sent successfully

**Comment by iFoxxy** [comment]
I am not sure, if this is the same issue, but my app doesn't receive notifications with production cert as well. With dev it works just fine. 
I'm completely sure that provisioning profile and push certs are configured correctly, is it possible that apple changed some configuration to production environment for push notifications providers and it doesn't work anymore?

**Comment by Dellybro** [comment]
This also an issue for me at the currnet moment

**Comment by Dellybro** [comment]
So what ended up happening for me is, i recreated the .certSigningKey, recreated the .cert, than grabbed the key from my keychains, than turned the p12 into .pem.

I think what happened was, I must've clicked on Development or something, If anybody else if having this issue, i recommend just making sure your .pem is correct

**Comment by dankimio** [comment]
@qiulang Are you still having this issue?

**Comment by NasrullahKhan** [comment]
yes i'm facing the same issue.
