### ISSUE TITLE
Feedback Service fails - Houston::Client.development.devices fails

### ISSUE THREAD

**Issue by jdraths** [nomad/houston#126]
running 

    Houston::Client.development.devices

fails for some reason. This has worked in the past with no issue. The returned error is:

    TypeError: no implicit conversion of nil into String
    from /usr/local/rvm/gems/ruby-2.3.0/gems/houston-2.2.3/lib/houston/connection.rb:39:in `initialize'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/houston-2.2.3/lib/houston/connection.rb:39:in `new'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/houston-2.2.3/lib/houston/connection.rb:39:in `open'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/houston-2.2.3/lib/houston/connection.rb:19:in `open'

**Comment by jdraths** [comment]
Also getting this error today:

    OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read finished A: sslv3 alert certificate unknown
    /usr/local/rvm/gems/ruby-2.3.0/gems/houston-2.2.3/lib/houston/connection.rb:44:in `connect'

**Comment by jdraths** [comment]
I updated openssl and regenerated my certificates today even though they weren't expired in Developer Member Center and the problem disappeared.

**Comment by nbastoWM** [comment]
Hi.
I'm using this gem and I'm getting this same error.
I regenerated the certificate, toggledbetween production and development, the notification is sent but when I try to get feedback I get:
```
TypeError (no implicit conversion of nil into String):
  houston (2.2.3) lib/houston/connection.rb:39:in `initialize'
  houston (2.2.3) lib/houston/connection.rb:39:in `new'
  houston (2.2.3) lib/houston/connection.rb:39:in `open'
  houston (2.2.3) lib/houston/connection.rb:19:in `open'

```

**Comment by dankimio** [comment]
Which version of OpenSSL and Ruby are you using? Can you try the same with the latest Ruby version?

**Comment by nbastoWM** [comment]
I tried with different Certificates, and Ruby 2.1.5 and 2.3.3.

**Comment by nbastoWM** [comment]
OK, I don't know why, but I assigned the service to a variable and now it is 

```
apn = Houston::Client.production
unregisteredDevices = apn.devices
```
