### ISSUE TITLE
Add Swift example to README.md

### ISSUE THREAD

**Issue by dankimio** [nomad/houston#133]

**Comment by BilalReffas** [comment]
What do you mean with Swift example? This is a ruby gem?

**Comment by dankimio** [comment]
See `Enabling Push Notifications on iOS` section in README. Currently it's written in Objective-C.

**Comment by BilalReffas** [comment]
Ah okay I will create a Pull Request

**Comment by BilalReffas** [comment]
Okay here is the pull request #136
