### ISSUE TITLE
Usage with APNs Authentication Key .p8 file

### ISSUE THREAD

**Issue by astamm78** [nomad/houston#139]
Is the Houston gem compatible with Apple's new authentication key workflow which outputs a .p8 file which never expires (unless revoked) and work for all deployment schemes?

I found a Node JS example that uses the new setup at the link below, was hoping that Houston would be able to provide ruby support.

http://126kr.com/article/5pxvuit047q

**Comment by adwebb** [comment]
Agreed this would be helpful if available

**Comment by dankimio** [comment]
Currently it doesn't, but I would be happy to accept a pull request with the feature.

**Comment by andrewarrow** [comment]
so I'm close to having this working in https://github.com/nomad/houston/pull/150

**Comment by andrewarrow** [comment]
well I think I need to look at https://github.com/igrigorik/http-2 tomorrow to finish this

**Comment by RamblinWreck77** [comment]
@andrewarrow Does p8push still work well? Are you using it in production?

**Comment by 1klap** [comment]
> @andrewarrow Does p8push still work well? Are you using it in production?

I was having issues with it, the version of `net-http2` seems to make problems when connecting to the APN endpoints. I forked it into the gem `klap_p8push` and can now talk to the sandbox endpoint. Not tested in production, so beware...

**Comment by alexshikov** [comment]
Just curious, if the command line version will support p8 at some point? The gem is neat! We just migrated to p8 from p12.

**Comment by talha-shoaib-vd** [comment]
Is it still in progress? I need to use P8 format in both sandbox and production

**Comment by 1klap** [comment]
I am still using my fork [klap_p8push](https://rubygems.org/gems/klap_p8push) in production, mentioned above and have currently no issues with it.
