### ISSUE TITLE
Cannot pass content-available = 0

### ISSUE THREAD

**Issue by noctivityinc** [nomad/houston#141]
For silent notifications we need to push content-available = 0 but the gen only seems to allow 1 or nothing. How do we fix this?

**Comment by dankimio** [comment]
@noctivityinc Thank you for reporting this. I'll take a look.

**Comment by paiv** [comment]
This seems like by design.

From [Payload Key Reference](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/PayloadKeyReference.html):

> **content-available** Number
> Include this key with a value of `1` to configure a silent notification.
