### ISSUE TITLE
How Does Houston Encode Push Tokens?

### ISSUE THREAD

**Issue by bennettl** [nomad/houston#145]
Here's an example of a push token I pass to Houston `2d03c5c2a6e0c47a4cba1de0738ee887`. I was wondering how exactly does houston encodes this to a valid 32 byte push token? I need to have a valid push token to further debug an issue I'm having. Looking through the source code i see the line `[1, 32, @token.gsub(/[<\s>]/, '')].pack('cnH64')`. Is this how it's done?

**Comment by dankimio** [comment]
Yes. It returns the binary representation of the device token. More about pack [here](https://www.rubydoc.info/stdlib/core/Array:pack). Another example in the [other library](https://github.com/calonso/ruby-push-notifications/blob/master/lib/ruby-push-notifications/apns/apns_notification.rb).
