### ISSUE TITLE
Where do you recommend we store the pem key?

### ISSUE THREAD

**Issue by krzkrzkrz** [nomad/houston#148]
In the guide it says: `/path/to/apple_push_notification.pem`. Where do you recommend we store this pem key? 

Using Rails, do we keep it at the application root level? Where is a sensible place?

**Comment by dankimio** [comment]
You can store the certificate in environment variable. Rails 5.1.0 will support [encrypted secrets](http://weblog.rubyonrails.org/2017/2/23/Rails-5-1-beta1/).

**Comment by krzkrzkrz** [comment]
Im referring to the pem file btw, not the key

**Comment by dankimio** [comment]
There's no need to store it anywhere. You can save it to environment variable `APN_CERTIFICATE_DATA` and houston will fetch it automatically.
