### ISSUE TITLE
Should support multi-topics certificate?

### ISSUE THREAD

**Issue by datdojp** [nomad/houston#149]
Firstly, thanks for the great library. It helped me a lot.

Last week, I had struggled with the push for 3 days. The iOS guys gave me new iOS certificates and ask me to update current certificates on server. Everything worked fine except that iOS app didn't receive the push. The `notification.error` was empty.

I investigated and figured out that the iOS certificate was a multi-topics one which contains 2 bundle ids for both staging and production environments. Unfortunately, `houston` doesn't support specifying `apns-topic` header, so I asked iOS guy to give a single-topic certificate and it worked like a charm.

I wonder if we should allow specifying bundle id so that library can work with multi-topics certificates.

Thanks.

**Comment by joshuachestang** [comment]
Currently on the second day of struggling with this. I've tried everything. Scoured every stackoverflow / forum related topic to this issue of the notification not being received from APN houston, but yet working flawlessly from the command line. Are there any alternatives to sending notifications via Rails?

**Comment by dankimio** [comment]
@joshuachestang try Rpush.
