### ISSUE TITLE
Exception sending notification: getaddrinfo: nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by MayankLogiciel** [nomad/houston#153]
![screen shot 2017-06-21 at 10 31 37 am](https://user-images.githubusercontent.com/8719380/27368032-e20c2b20-566d-11e7-9259-84e332898d83.png)

I was able to send push successfully to device using command line. But it suddenly stopped working without any other changes as you can see in screenshot attached. is there any limitation that we can send only some number of notification during a time period or anything else. It happened to me several times.. sometimes it works and sometimes it doesn't work.

**Comment by hatched-SwetaSanghavi** [comment]
This was my issue when I encountered this: https://stackoverflow.com/questions/15213962/my-hosts-file-under-mac-os-x-10-8-is-empty
