### ISSUE TITLE
Getting nil back with no errors when APN.push(notification) and notification is not delivered.

### ISSUE THREAD

**Issue by hugoh59** [nomad/houston#157]
I'm not sure why this is happening but I'm not getting any response back just nil and no error message.

**Comment by justindunn** [comment]
I'm experiencing this issue now as well, it was working last week fine then all the sudden now its not.

**Comment by scanferla** [comment]
What is supposed to be returned when it works? I'm also getting `nil` when I do `APN.push(notification)`

**Comment by deepeeess** [comment]
I am seeing this as well.

**Comment by cyurtbil** [comment]
I'm seeing this as well. And I checked my certificates and generated push kit token by my ios app, they are working with apn push -c ... on command line. When I'm trying to do with Houston it doesn't send the notification and returns nil.

notification.error is nil as well

`class V1::APNSService

  def initialize(recipient)
    @@recipient = recipient
    @@apn = Houston::Client.production
    @@apn.certificate = File.read("pem_file_name.pem") # Encrypted with aes 256 option, I've set the APN_CERTIFICATE_PASSPHRASE to correct value, I've checked
    @@notification = Houston::Notification.new(device: @@recipient.device.voip_registration_id)
  end

  def set_options(notification_type, *args)
    case notification_type
    when PushNotificationType::VIDEO_CALLING
      meeting = args[0][:meeting]
      session = args[0][:session]
      @@notification.alert = "Incoming video call"
      @@notification.badge = 1
      @@notification.category = PushNotificationType::VIDEO_CALLING
      @@notification.custom_data = {meeting_id: meeting.id}
    end
    return self
  end

  def send
    @@apn.push(@@notification) unless @@recipient.device.nil? || @@recipient.suspended? || @@notification.nil?
  end
end`

**Comment by cyurtbil** [comment]
I'm seeing this as well. And I checked my certificates and generated push kit token by my ios app, they are working with apn push -c ... on command line. When I'm trying to do with Houston it doesn't send the notification and returns nil.

notification.error is nil as well

```
class V1::APNSService

  def initialize(recipient)
    @@recipient = recipient
    @@apn = Houston::Client.production
    # Encrypted with aes 256 option, I've set the APN_CERTIFICATE_PASSPHRASE to correct value, I've checked
    @@apn.certificate = File.read("pem_file_name.pem")
    @@notification = Houston::Notification.new(device: @@recipient.device.voip_registration_id)
  end

  def set_options(notification_type, *args)
    case notification_type
    when PushNotificationType::VIDEO_CALLING
      meeting = args[0][:meeting]
      @@notification.alert = "Incoming video call"
      @@notification.badge = 1
      @@notification.category = PushNotificationType::VIDEO_CALLING
      @@notification.custom_data = {meeting_id: meeting.id}
    end
    return self
  end

  def send
    @@apn.push(@@notification)
  end
end
```

**Comment by cyurtbil** [comment]
The problem with my code was on the iOS side. I have been saving my code without spices and closing brackets.

Please save your token at this format
<ce8be627 2e43e855 16033e24 b4c28922 0eeda487 9c477160 b2545e95 b68b5969>

As soon as I fixed the token format, it started working.

**Comment by dfabreguette-ap** [comment]
Got exact same problem ! Reformating token didn't work either...

**Comment by dfabreguette-ap** [comment]
I'll give a try to set a password to pem file, thanks @jeffmcfadden !

**Comment by acruis** [comment]
From reading a bit further, this is the same problem as #72, and there already is PR #73 which attempts to deal with it using a timeout.

**Comment by SunnyIzr** [comment]
Any plans to fix this in the near future?

**Comment by thovt93** [comment]
I got exact same problem

**Comment by matias09** [comment]
Hi To all,
  I got the same problems with Houston,
  I was sending push notifications with no
  response if the Token that I sent was valid or not.

  Playing with the file "houston-2.4.0/lib/houston/client.rb\"
  I modified the method Push() as this: 

```ruby
    def push(*notifications)
      return if notifications.empty?

      notifications.flatten!

      Connection.open(@gateway_uri, @certificate, @passphrase) do |connection|
        ssl = connection.ssl

        notifications.each_with_index do |notification, index|
          next unless notification.kind_of?(Notification)
          next if notification.sent?
          next unless notification.valid?

          notification.id = index

          connection.write(notification.message)
          notification.mark_as_sent!

          ready = IO.select([ssl], nil, nil, 10)
          if !ready
            return true
          else
            error = connection.read(6)

            _command, status, index = error.unpack('ccN')
            notification.apns_error_code = status
            notification.mark_as_unsent!

            return false
          end
        end
      end
    end
```
  Basically the main change is add a timeout on "IO.select()" and
  check if the return has something.

I hope this comment be useful 
Greetings
