### ISSUE TITLE
My APN are rate limited to one per 20-25 seconds

### ISSUE THREAD

**Issue by stevenjwolfman** [nomad/houston#162]
If I send 100 PN, every 25 seconds, 1 of the messages is delivered until they are all delivered. Has anyone had this experience before?

**Comment by dankimio** [comment]
Could [this](https://developer.apple.com/library/archive/technotes/tn2265/_index.html#//apple_ref/doc/uid/DTS40010376-CH1-TNTAG23) be the issue?
