### ISSUE TITLE
Expiry field is not documented

### ISSUE THREAD

**Issue by Fiser12** [nomad/houston#173]
Hello to all

I see that in the code exists the expiry field in the notification but this one it doesn't appear how to use it in the documentation. Could somebody help me with that? it's very important feature for our application.

**Comment by toineheuvelmans** [comment]
@Fiser12 I do not have an answer for you but please also be aware of https://github.com/nomad/houston/issues/171. For as far as I know, unless that's addressed Houston will break this November.

**Comment by Fiser12** [comment]
oh thanks!
