### ISSUE TITLE
Persisted connections are not re-connecting in case they are dropped

### ISSUE THREAD

**Issue by hubertlepicki** [nomad/houston#76]
This is not entirely Houston's fault, but the way Ruby Sockets work. When the server looses connection to Apple gateways, Houston knows nothing about it and connection#open? will still return true. Moreover, you seem to be able to write to such dead connection, yet nothing is delivered to Apple.

Underlying TCPConnection that is being opened to Apple is not working properly, yet we know nothing about it.

I have too little experience with Ruby TCP programming to solve it myself. But if someone can point me to right direction I could create a patch and pr.

Any ideas how to solve this?

**Comment by ferrous** [comment]
A multithread wrap with reset on CLOSE_WAIT connections
https://gist.github.com/ferrous/d498971be300683c3bbd
