### ISSUE TITLE
Push Notifications reported as sent and without error but not received in case of ~ 20 notifications

### ISSUE THREAD

**Issue by j4zz** [nomad/houston#79]
In case we send a certain amount of push notifications, they don’t seem to be delivered correctly. Everything works correctly for a lower amount of push notifications. We do not use [persistent connections](https://github.com/nomad/houston#persistent-connections).

Here’s some very rough logging code that we had in place:

``` ruby
    client.push(*notifications)
    Rails.logger.info "PNS Job (1/2): Send #{notifications.length} notifications. Notification Sample: #{notifications.first.inspect}. Errors: #{notifications.collect(&:error).compact}. Sent: #{notifications.collect(&:sent?)}"
    Rails.logger.info "PNS Job (2/2): #{client.devices}, Push Infos: #{push_options.inspect}"
```

All following examples were created with the production build of the app, using the production certificate and Houston production client with houston 2.2.1.

Here’s the log output of a _working example_. As you can see, the errors are empty and both notifications are reported as being sent, and they are correctly received on both clients.

``` ruby
PNS Job (1/2): Send 2 notifications. Notification Sample: #<Houston::Notification:0x000000070bb240 @token="<REPLACED>", @alert="Some Text", @badge=1, @sound=nil, @category=nil, @expiry=nil, @id=0, @priority=nil, @content_available=true, @custom_data={:custom_data=>{:rscs=>[{REPLACED}]}}, @sent_at=2014-09-26 10:15:13 +0200>.
Errors: []. Sent: [true, true]
PNS Job (2/2): [], Push Infos: {:alert=>"Some Text", :badge=>1, :content_available=>true, :custom_data=>{:rscs=>[{REPLACED}]}}
```

Here’s the log output of an _example that does not work_. Again, the errors are empty and all notifications are reported as being sent, but they are not in fact received on the target devices. The target devices include the two devices from the previous working example:

``` ruby
PNS Job (1/2): Send 23 notifications. Notification Sample: #<Houston::Notification:0x0000000c8dc488 @token="<REPLACED>", @alert="Some Alert", @badge=1, @sound=nil, @category=nil, @expiry=nil, @id=0, @priority=nil, @content_available=true, @custom_data={:custom_data=>{:rscs=>[{REPLACED}]}}, @sent_at=2014-09-29 15:33:36 +0200>.
Errors: []. Sent: [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true]
PNS Job (2/2): [], Push Infos: {:alert=>"Some Alert", :badge=>1, :content_available=>true, :custom_data=>{:rscs=>[{REPLACED}]}}
```

What could be the source of the error or what else could we look into to narrow down the problem?

**Comment by LuizEdgar** [comment]
Hello, this issue was solved? If no, how are you handling this?

**Comment by kaneda** [comment]
@LuizEdgar, not to the best of my knowledge, instead I send each notification separately to users instead of en masse.

**Comment by LuizEdgar** [comment]
Thanks @kaneda.

Well... but Apple says that it can be considered as an DoS Attack. 

"Keep your connections with APNs open across multiple notifications; don’t repeatedly open and close connections. APNs treats rapid connection and disconnection as a denial-of-service attack. You should leave a connection open unless you know it will be idle for an extended period of time—for example, if you only send notifications to your users once a day it is ok to use a new connection each day."

How bad can it be? How many notifications are you sending per day?

**Comment by kaneda** [comment]
@LuizEdgar it could be considered a DoS attack. I'm not sending many, in the hundreds.
