### ISSUE TITLE
Number in a payload delivered as NSString

### ISSUE THREAD

**Issue by borkasm** [nomad/houston#86]
When I send a notification like this

```
apn push fcc3551cd74e40d45beb109946a6ca6dc7423e16dd042e2b2aa06f07183d5b8c -c apns-dev-cert.pem -m "Credits" -d credits=100
```

payload's `credits:` value is delivered as instance of NSString but not a NSNumber

**Comment by jayesh15111988** [comment]
@intrigua How did you manage to send a JSON payload with push notifications? I am trying to send standard json as a payload from command line, but getting an exception parsing a JSON. @mattt Any help would be much appreciate.

**Comment by jdraths** [comment]
@jayesh15111988 why not just convert the JSON payload to NSNumber or Int on the client and not worry about whether the JSON payload represents the number as a string or integer?

**Comment by jayesh15111988** [comment]
@jdraths My question was not about data type of JSON payload integer vs string. I was just curious to find out how to send JSON data as push payload through Houston.

**Comment by jdraths** [comment]
@jayesh15111988 use -p to send a json payload [per this code.](https://github.com/nomad/houston/blob/master/bin/apn#L31)

`$ apn push "<token>" -c /path/to/apple_push_notification.pem -m "Hello from the command line! " -p {"your_json": "value", "more_json": "more values", "integer": 1}`
Not sure if my format is right but it's close.
