### ISSUE TITLE
Houston::Client.production.devices raises exception

### ISSUE THREAD

**Issue by davidpdrsn** [nomad/houston#91]
I get the following error when I call `Houston::Client.production.devices` from the rails console.

```
[2] pry(main)> Houston::Client.production.devices
TypeError: no implicit conversion of nil into String
from /app/vendor/bundle/ruby/2.2.0/gems/houston-2.2.3/lib/houston/connection.rb:39:in `initialize'
```

**Comment by kaneda** [comment]
Hey @davidpdrsn, it looks like you're trying to do this without first defining the passphrase or certificate. If you were to create an APN in the environment file itself, for instance, and then invoke it, e.g. ```YourApp::Application.config.your_apn.devices``` you would see that it works.

**Comment by davidpdrsn** [comment]
That fixed it! Thanks :smile:
