### ISSUE TITLE
Silent failure due to environment/certificate incompatibility

### ISSUE THREAD

**Issue by iandonovan** [nomad/houston#93]
I've fixed this issue, but I reckon it might be good to leave a note of it here:

I was getting silent failures when sending push notifications -- the `notification` object, after calling `push()`, had no errors on it, but nothing was being sent out. After a bit of digging, I noticed that it was because I had the client set as `Houston::Client.production` (to match the Rails environment), where the certificate file was not for a production environment. Switching over to `Houston::Client.development` fixed the problem.

I know this isn't Houston's issue, per se, but I did notice that folks were having problems with silent failures. This might be a lead for some of you. I don't even know if it's possible for Houston to look at the certificate and determine its proper environment, then alert me of a mismatch, but I hope this helps people in the interim.

**Comment by courtsimas** [comment]
Could be worth submitting a PR to the Readme - maybe in a reminder section at the bottom, so people read it there, and once it's merged in, close the issue so it doesn't look like there's an open issue for this.

:+1: good find.

**Comment by dkniffin** [comment]
I just ran into this problem as well. It turns out it's not related to the environment the cert is created for; it's the iOS provisioning profile.

**Comment by adeeb1** [comment]
I run into this problem more than I should. What I always miss is specifying the correct iOS provisioning profile. Make sure that the provisioning profile that you specify for your app has Push Notifications enabled in the "Capabilities" tab of your Target in Xcode.

**Comment by bbrookler** [comment]
I had an issue sending via command line, adding '-e production' fixed it for me.
