### ISSUE TITLE
Exception while sending Push Notification to device

### ISSUE THREAD

**Issue by amar28187** [nomad/houston#96]
Hi,

Any update on this please?

I was testing out push notification using the procedure mentioned here. I was able to send a notification to the device with certificates, .p12 and .pem of my personal apple developer account.

But when I was trying with my company's certificates, .p12 and .pem (which I think are password protected), I get the following error.

    Exception sending notification: SSL_connect returned=1 errno=0 state=SSLv3 read finished A: sslv3 alert certificate unknown

What could be the issue and how to solve this? I am sending notifications via CLI using

    $ apn push "<token>" -c /path/to/apple_push_notification.pem -m "Hello from the command line!"

Also, as a small note, the command is not correctly taking the string if it has '!' in it.

Thanks,
Amar

**Comment by andrey2ag** [comment]
Hi, did you resolve the problem?

**Comment by DrJid** [comment]
Getting this too. Was this and resolved.. and if so, do you know how?

**Comment by dankimio** [comment]
What version of OpenSSL are you using?
