### ISSUE TITLE
UI Limit of 30 keys appear in a collection ( table and new form )

### ISSUE THREAD

**Issue by keyscores** [nomad/houston#97]
I've noticed collections have a max of 30 keys (29 + _id) in the UI
- This is true for the table, on the collection view. 
- It is also true for  a "New" document.
Seems a bit arbitrary which keys are present and which are truncated.

As a UI suggestion:
New document form: it could be nice to have the keys be a dropdown combo. This would avoid having to list all the possible keys.
Also it's missing the ability to create a new/arbitrary, key.

**Comment by mattt** [comment]
What? This is a command-line utility and gem. There's no UI.
