### ISSUE TITLE
Is a passphrase needed?

### ISSUE THREAD

**Issue by guyisra** [nomad/houston#98]
Using the Houston Client, notifications are sent without providing a passphrase, but when using 

connection = Houston::Connection.new(Houston::APPLE_DEVELOPMENT_GATEWAY_URI, certificate, passphrase)

a passphrase is needed.

Why? Is it needed? I see code of various projects that some provide a passphrase and some don't...

**Comment by j4zz** [comment]
If your certificate is protected by a passphrase, you need to pass it here. Otherwise, you can pass nil for the passphrase, which seems to be the case for you.

`Houston::Connection.new(apns_gateway, apns_cert_file, nil)`
