### ISSUE TITLE
The Way To Get OpenSSL::SSL::SSLError

### ISSUE THREAD

**Issue by iBcker** [nomad/houston#99]
when use Houston::Connection to send push with some tokens 
if any token is invalid,after then invalid token write to connect, you may get the error("OpenSSL::SSL::SSLError: SSL_write: bad write retry"),but the connect is still keep alive,i think this is a but ,because when apns service get the invalid token ,it will cancel the connect .

houston version:2.2.1

**Comment by iBcker** [comment]
the error detail

OpenSSL::SSL::SSLError: SSL_write: bad write retry
	from /home/deployer/.rbenv/versions/2.0.0-p451/lib/ruby/2.0.0/openssl/buffering.rb:319:in `syswrite'
	from /home/deployer/.rbenv/versions/2.0.0-p451/lib/ruby/2.0.0/openssl/buffering.rb:319:in `do_write'
	from /home/deployer/.rbenv/versions/2.0.0-p451/lib/ruby/2.0.0/openssl/buffering.rb:337:in `write'
	from /home/deployer/apps/xxxx/releases/20150604102058/lib/apn_connection.rb:26:in `write'

**Comment by iBcker** [comment]
i try in console ,get the some

**Comment by rubyrider** [comment]
Any solution?
